### ISSUE TITLE
json file and model 

### ISSUE THREAD

**Issue by luoww1992** [nefeliandreou/PoseRepresentation#1]
where is the json and model file ?

**Comment by nefeliandreou** [comment]
Hi! For the model we have adopted the following codebases https://github.com/papagina/Auto_Conditioned_RNN_motion and https://github.com/facebookresearch/QuaterNet/tree/main. Which json are you referring to?

**Comment by luoww1992** [comment]
Q1: these are many json files, what the different is ?   different action ?  and how to get it ?
Q2: the skeleton looks like smplh ? the input bvh file skeleton must have the same skeleton hierarchy as target skeleton ?
Q2.1 if is not smplh, which skeleton type ? 
Q3: how to dispose the bvh file, get 3D world position ?
----- 原始邮件 -----
发件人：nefeliandreou ***@***.***>
收件人：nefeliandreou/PoseRepresentation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [nefeliandreou/PoseRepresentation] json file and model  (Issue #1)
日期：2023年06月28日 15点22分


Hi! For the model we have adopted the following codebases https://github.com/papagina/Auto_Conditioned_RNN_motion and https://github.com/facebookresearch/QuaterNet/tree/main. Which json are you referring to?

&mdash;

**Comment by luoww1992** [comment]
what are your libs:code1, rhythmdata and rhythmnet ?
i find some , but looks like wrong, can you share your libs url ?
----- 原始邮件 -----
发件人：nefeliandreou ***@***.***>
收件人：nefeliandreou/PoseRepresentation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [nefeliandreou/PoseRepresentation] json file and model  (Issue #1)
日期：2023年06月28日 15点22分


Hi! For the model we have adopted the following codebases https://github.com/papagina/Auto_Conditioned_RNN_motion and https://github.com/facebookresearch/QuaterNet/tree/main. Which json are you referring to?

&mdash;

**Comment by nefeliandreou** [comment]
1. Different json files correspond to different representations, loss weights and so on that you can build depending on the model you want to test out. 
2. The template skeleton is not SMPLH. We are using data from the CMU dataset, therefore we use the template bvh from there. You can find more information about which subjects we use exactly in the paper. 
3. You can extract the 3D position from the dual-quaternions (with current coordinate system) using [this](https://github.com/nefeliandreou/PoseRepresentation/blob/5dcb6756e6e4f11be11f77e1a272aa2a53d69af6/src/dualquats.py#L435C7-L435C7) function. 

You might have to restructure the eval.py file so that you can use the functions from dualquats by replacing 
`from code1.dualquats import currentdq2localquats ` with `from dualquats import currentdq2localquats`. You will have to also define your dataloader and network init functions (I can help you on that). In this codebase, we just provide the tools to convert between the representations.

**Comment by luoww1992** [comment]
1, can you share me a json file and dataset, i want to edit  eval.py by it. and needs libs: code1, rhythmdata and rhythmnet
2, the input bvh file skeleton must have the same skeleton hierarchy as target skeleton ?
3, can i use smpl24 skts to retarget the retarget skt ? if yes, how to edit one-to-one skeleton index or other code ?
----- 原始邮件 -----
发件人：nefeliandreou ***@***.***>
收件人：nefeliandreou/PoseRepresentation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [nefeliandreou/PoseRepresentation] json file and model  (Issue #1)
日期：2023年06月28日 17点04分



Different json files correspond to different representations, loss weights and so on that you can build depending on the model you want to test out.
The template skeleton is not SMPLH. We are using data from the CMU dataset, therefore we use the template bvh from there. You can find more information about which subjects we use exactly in the paper.
You can extract the 3D position from the dual-quaternions (with current coordinate system) using this function.

You might have to restructure the eval.py file so that you can use the functions from dualquats by replacing

from code1.dualquats import currentdq2localquats  with from dualquats import currentdq2localquats. You will have to also define your dataloader and network init functions (I can help you on that). In this codebase, we just provide the tools to convert between the representations.

&mdash;

**Comment by nefeliandreou** [comment]
1. You can acquire the dataset from [here](https://sites.google.com/a/cgspeed.com/cgspeed/motion-capture/the-motionbuilder-friendly-bvh-conversion-release-of-cmus-motion-capture-database). The json file will depend on the dataloader and model initiator functions that you will define. I can share with you the ones I used, but you will have to modify it depending on your functions.
2. Yes, input and target must be the same. 
3. Potentially yes. Please look into [this](https://github.com/kasvii/joints2smpl).

**Comment by luoww1992** [comment]
i have download a dataset, but this is only some bvh files,
can you give me a sample of your dataset with json and other libs ?
i am editing...
----- 原始邮件 -----
发件人：nefeliandreou ***@***.***>
收件人：nefeliandreou/PoseRepresentation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [nefeliandreou/PoseRepresentation] json file and model  (Issue #1)
日期：2023年06月28日 17点28分



You can acquire the dataset from here. The json file will depend on the dataloader and model initiator functions that you will define. I can share with you the ones I used, but you will have to modify it depending on your functions.
Yes, input and target must be the same.
Potentially yes. Please look into this.


&mdash;

**Comment by nefeliandreou** [comment]
My dataset is the exact sample of bvh files that I sent you. I will try to provide you with a json later today. The libraries that relate to model and data loading you will have to define them yourself.

**Comment by nefeliandreou** [comment]
A  sample config file looks like this:
{  "visdom_title": "v1-test",
  "model": "dq_acLSTM",
  "acRNN_model": "vanilla",
  "data_type": "dualquats",

  "paired_dir": <train_data_path>,
  "test_paired_dir": <test_data_path>,
   "validation_paired_dir": <val_data_path>,
  
 "order": "zyx",
"fps_current":120,
"fps_target":30,
  "QRL_local": false,
  "QRL_curr": false,
  "DL": true,
  "BL": false,
  "ortho6D_loss": false,
  "mse_loss":true,
  "push_seq":"86_06",


  "save_bvh_dir": <path_to_save_bvh>,
  "save_weights_dir": <path_for_net_weights_save>,
  "train_read_weight_path": "",
  "bvh_skeleton_file_name": <default_skeleton_path>,

  "save_weights_every": 10000,
  "save_bvh_every": 1000,
  "norm_type": "all",
  "foot_contact": false,

  "test_generate_seq_num": 3000,
  "test_save_bvh_dir":  <path_to_save_bvh_test>,
  "test_read_weight_path": <path_for_net_weights_load>
}
As I said before, this is specific to our network initialization function.
